FileVersion = 1

[Project]
Name = "snappyc-beef"
DefaultNamespace = "snappyc"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\snappyc_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\snappyc.lib"]
